- name: Install dependencies
  run: |
    mkdir -p "$HOME/.local/bin"
    curl -O 'https://download.imagemagick.org/ImageMagick/download/binaries/magick'
    chmod u+x magick
    mv magick "$HOME/.local/bin"
    echo "$HOME/.local/bin" >> "$GITHUB_PATH"
- name: Check dependencies
  run: magick -version